In [1]:
import numpy as np
basicZeros = np.zeros((2,3))
basicZeros


array([[0., 0., 0.],
       [0., 0., 0.]])

In [2]:
basicZeros[0, 0] = 12
basicZeros

array([[12.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [3]:
basicEmpty = np.empty((2,3))
basicEmpty[0, 0] = 12

array([[12.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [4]:
basicEmpty[0, 1] = 13

In [5]:
basicEmpty

array([[12., 13.,  0.],
       [ 0.,  0.,  0.]])

# Testing for Unigram and Bigram

In [1]:
from collections import Counter

In [3]:
testString = "I am sam, sam I am, I do not like green eggs and ham"
counter = Counter(testString)
counter
# Counter class won't work


Counter({'I': 3,
         ' ': 13,
         'a': 6,
         'm': 5,
         's': 3,
         ',': 2,
         'd': 2,
         'o': 2,
         'n': 3,
         't': 1,
         'l': 1,
         'i': 1,
         'k': 1,
         'e': 4,
         'g': 3,
         'r': 1,
         'h': 1})

In [11]:
from collections import defaultdict
import nltk
from nltk.tokenize import word_tokenize

In [14]:
words = [x.lower() for x in word_tokenize(testString)]

In [16]:
words_unigram = Counter(words)
words_unigram

Counter({'i': 3,
         'am': 2,
         'sam': 2,
         ',': 2,
         'do': 1,
         'not': 1,
         'like': 1,
         'green': 1,
         'eggs': 1,
         'and': 1,
         'ham': 1})

In [10]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\gilwo\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.


True

In [13]:
x = 'HELLO'.lower()
x

'hello'